#library "map15.acs"
#include "zcommon.acs"

int volumetric_fog_count = 34;
int volumetric_fog_mapper[34] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,30,31,32,33,40,50,51};

script 100 ENTER{
	/* set fog/fade */
	for(int a=0;a<volumetric_fog_count;a++){
		Sector_SetFade(volumetric_fog_mapper[a],87,0,0);
	}
	
	/* lower start support */
	log(s:"lower start platform:");
	Floor_LowerInstant(16,0,49);
	

	
}

script 1(int floorIndex, int lineIndex){
	
}

